version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: cargo
    directory: userspace/ksud
    schedule:
      interval: daily
    allow:
      - dependency-type: "all"

  - package-ecosystem: gradle
    directory: manager
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: website
    schedule:
      interval: daily
