version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: cargo
    directory: userspace/ksud
    schedule:
      interval: daily
    allow:
      - dependency-type: "all"
    groups:
      crates:
        patterns:
          - "*"
  - package-ecosystem: gradle
    directory: manager
    schedule:
      interval: daily
    groups:
      maven-dependencies:
        patterns:
          - "*"
  - package-ecosystem: npm
    directory: website
    schedule:
      interval: daily
