name: Build debug kernel
on:
  workflow_dispatch:

jobs:
  build-debug-kernel-a12:
    uses: ./.github/workflows/gki-kernel.yml
    with:
      version: android12-5.10
      version_name: android12-5.10.209
      tag: android12-5.10-2024-05
      os_patch_level: 2024-05
      patch_path: "5.10"
      debug: true
  build-debug-kernel-a13:
    strategy:
      matrix:
        include:
          - version: "5.10"
            sub_level: 214
            os_patch_level: 2024-07
          - version: "5.15"
            sub_level: 149
            os_patch_level: 2024-07
    uses: ./.github/workflows/gki-kernel.yml
    with:
      version: android13-${{ matrix.version }}
      version_name: android13-${{ matrix.version }}.${{ matrix.sub_level }}
      tag: android13-${{ matrix.version }}-${{ matrix.os_patch_level }}
      patch_path: ${{ matrix.version }}
      debug: true
  build-debug-kernel-a14:
    strategy:
      matrix:
        include:
          - version: "5.15"
            sub_level: 153
            os_patch_level: 2024-07
          - version: "6.1"
            sub_level: 84
            os_patch_level: 2024-07
    uses: ./.github/workflows/gki-kernel.yml
    with:
      version: android14-${{ matrix.version }}
      version_name: android14-${{ matrix.version }}.${{ matrix.sub_level }}
      tag: android14-${{ matrix.version }}-${{ matrix.os_patch_level }}
      patch_path: ${{ matrix.version }}
      debug: true